version: '2'
services:
  wordpress:
    image: wordpress
    cpu_shares: 100
    mem_limit: 124288000
    environment:
      WORDPRESS_DB_PASSWORD: password
      #WORDPRESS_DB_USER:
      #WORDPRESS_DB_NAME:
    ports:
      - "80:80"
    links:
      - mysql
  mysql:
    image: mysql
    cpu_shares: 100
    mem_limit: 124288000
    environment:
      MYSQL_ROOT_PASSWORD: password
      
